name: Déploiement 🚀
run-name: ${{ github.actor }} is deploying online ! 🚀
on: push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ip }}/www
        port: 21
        username: ${{ secrets.name }}
        password: ${{ secrets.mdp }}
        local-dir: './'
        exclude: vendor/
